### ISSUE TITLE
Wrong remote

### ISSUE THREAD

**Issue by e-minguez** [electricduck/sodalite#7]
```
sudo ostree pull sodalite/stable/x86_64/default
```
Complains about remote not found. `ostree remote refs zio` shows:

```
zio:fedora/35/x86_64/sodalite
zio:sodalite/stable/x86_64/base
```

**Comment by electricduck** [comment]
Fixed in 6e5ce466a739f540e7be64dcea8f44848f70164c. This is what I get for writing up READMEs at around 5AM in the morning :laughing:.
