### ISSUE TITLE
[Recommendation] Compose Tree without --unified-core flag

### ISSUE THREAD

**Issue by ACertainTopfi** [electricduck/sodalite#9]
Looking at the repository, it appears that `rpm-ostree compose` was executed with the `--unified-core` flag.
As it stands, the codepath employed when setting that flag is causing a bug that adds additional folders to the repository. These folders generally do not cause issues when rebasing a Silverblue install, however, they can lead to installer images build via that repository to fail installation.

More on this here: https://github.com/coreos/rpm-ostree/issues/3270

I would recommend that until this issue is addressed, using the legacy codepath (running `rpm-ostree compose` without `--unified-core`) would be advisable.

Note: I am currently cobbling together a small script that should create a bootable installer image so Sodalite can be directly installed without the need for rebasing. Am currently building an image using a self composed tree without the unified codepath and will open a merge request with the script used, once I have tested that it works reliably. I very much believe that a Silverblue base plus Pantheon has a lot of potential and actually worked on something [similar](https://www.reddit.com/r/elementaryos/comments/rk38sz/i_made_an_immutable_elementary_os_installer_image/) over the past few weeks. Sodalite goes at such a project from a different direction, with each approach potentially complementing each other, so perhaps we can collaborate on that.

**Comment by electricduck** [comment]
Hah, that's so incredibly bizzare we seemed to have worked on the same thing at roundabout the same time. Funnily enough, I did briefly try to cobble together a `lorax` command to test how it works but ran into all sorts of issues. A bootable ISO was never really a high priority for me, however, so I never took the project any further.

As you can probably guess, I'm using the `--unified-core` flag purely because `rpm-ostree` told me to and never really looked into it properly, and with good reason, since the build fails to work for me. With `--unified-flag` omitted the build eventually crashes right after the post script(s):

```
Created symlink /etc/systemd/system/multi-user.target.wants/touchegg.service → /usr/lib/systemd/system/touchegg.service.
Finished postprocessing script
Initializing rootfs
Moving /usr to target
Copying toplevel compat symlinks
Migrating /usr/etc/passwd to /usr/lib/
Migrating /usr/etc/group to /usr/lib/
error: Finalizing rootfs: Converting /var to tmpfiles.d: Analyzing /var/lib content: failed to find user ID '976'
error: Failed to build tree
```

Using the commands:

```
rpm-ostree compose tree \
    --repo="./src" \
    $treefile
```

So not entierly sure what other edits you've done to the treefile?

**Comment by ACertainTopfi** [comment]
Honestly made no modifications to the treefile. For testing, I just cloned the git repository again and ran the build.sh found inside the scripts directory with `--unified-core` removed. I did so on a fresh install of Fedora 35 Workstation via KVM. The tree was composed successfully.

I have made the experience that sometimes compose can fail, even though there is no discernible reason for it happening, which is why I now exclusively compose on fresh VMs. Perhaps that is the case here?

For reference, here is what the log spits out after finishing postprocessing stage:

```
Created symlink /etc/systemd/system/multi-user.target.wants/touchegg.service → /usr/lib/systemd/system/touchegg.service.
Finished postprocessing script
Initializing rootfs
Moving /usr to target
Copying toplevel compat symlinks
Recompiling policy
Migrating /usr/etc/passwd to /usr/lib/
Migrating /usr/etc/group to /usr/lib/
SELinux policy in /var, enabling workaround
Ignoring non-directory/non-symlink 'var/log/lastlog'
Ignoring non-directory/non-symlink 'var/log/README'
Ignoring non-directory/non-symlink 'var/cache/ldconfig/aux-cache'
Ignoring non-directory/non-symlink 'var/cache/app-info/cache/de_AT.cache'
Ignoring non-directory/non-symlink 'var/cache/ibus/bus/registry'
Ignoring non-directory/non-symlink 'var/lib/alternatives/libnssckbi.so.x86_64'
Ignoring non-directory/non-symlink 'var/lib/alternatives/soelim'
Ignoring non-directory/non-symlink 'var/lib/alternatives/qtchooser-5'
Ignoring non-directory/non-symlink 'var/lib/alternatives/qtchooser-default'
Ignoring non-directory/non-symlink 'var/lib/alternatives/iptables'
Ignoring non-directory/non-symlink 'var/lib/alternatives/ebtables'
Ignoring non-directory/non-symlink 'var/lib/alternatives/arptables'
Ignoring non-directory/non-symlink 'var/lib/alternatives/ld'
Ignoring non-directory/non-symlink 'var/lib/alternatives/print'
Ignoring non-directory/non-symlink 'var/lib/alternatives/cifs-idmap-plugin'
Ignoring non-directory/non-symlink 'var/lib/alternatives/xinputrc'
Ignoring non-directory/non-symlink 'var/lib/alternatives/ifup'
Ignoring non-directory/non-symlink 'var/lib/alternatives/cups_backend_smb'
Ignoring non-directory/non-symlink 'var/lib/alternatives/man'
Ignoring non-directory/non-symlink 'var/lib/alternatives/man.7.gz'
Ignoring non-directory/non-symlink 'var/lib/alternatives/libwbclient.so.0.15-64'
Ignoring non-directory/non-symlink 'var/lib/ufw/user.rules'
Ignoring non-directory/non-symlink 'var/lib/ufw/user6.rules'
Ignoring non-directory/non-symlink 'var/lib/authselect/user-nsswitch-created'
Ignoring non-directory/non-symlink 'var/lib/sss/db/config.ldb'
Ignoring non-directory/non-symlink 'var/lib/xkb/README.compiled'
Ignoring non-directory/non-symlink 'var/lib/gdm/.config/pulse/default.pa'
Adding rpm-ostree-0-integration.conf
Preparing kernel
Creating empty machine-id
dracut: Executing: /usr/bin/dracut --reproducible --gzip -v --add ostree --tmpdir=/tmp/dracut -f /tmp/initramfs.img --no-hostonly --kver 5.15.13-200.fc35.x86_64
dracut: dracut module 'busybox' will not be installed, because command 'busybox' could not be found!
dracut: dracut module 'rngd' will not be installed, because command 'rngd' could not be found!
dracut: dracut module 'dmraid' will not be installed, because command 'dmraid' could not be found!
dracut: dracut module 'multipath' will not be installed, because command 'multipath' could not be found!
dracut: dracut module 'tpm2-tss' will not be installed, because command 'tpm2' could not be found!
dracut: dracut module 'nvmf' will not be installed, because command 'nvme' could not be found!
dracut: dracut module 'biosdevname' will not be installed, because command 'biosdevname' could not be found!
mknod: /tmp/dracut/dracut.IR6W0S/initramfs/dev/null: Operation not permitted
mknod: /tmp/dracut/dracut.IR6W0S/initramfs/dev/kmsg: Operation not permitted
mknod: /tmp/dracut/dracut.IR6W0S/initramfs/dev/console: Operation not permitted
mknod: /tmp/dracut/dracut.IR6W0S/initramfs/dev/random: Operation not permitted
mknod: /tmp/dracut/dracut.IR6W0S/initramfs/dev/urandom: Operation not permitted
dracut: *** Including module: bash ***
dracut: *** Including module: systemd ***
dracut: *** Including module: systemd-initrd ***
dracut: *** Including module: modsign ***
dracut: *** Including module: nss-softokn ***
dracut: *** Including module: i18n ***
dracut: *** Including module: drm ***
dracut: *** Including module: plymouth ***
dracut: *** Including module: btrfs ***
dracut: *** Including module: crypt ***
dracut: *** Including module: dm ***
dracut: Skipping udev rule: 64-device-mapper.rules
dracut: Skipping udev rule: 60-persistent-storage-dm.rules
dracut: Skipping udev rule: 55-dm.rules
dracut: *** Including module: kernel-modules ***
dracut: *** Including module: kernel-modules-extra ***
dracut: *** Including module: lvm ***
dracut: Skipping udev rule: 64-device-mapper.rules
dracut: Skipping udev rule: 56-lvm.rules
dracut: Skipping udev rule: 60-persistent-storage-lvm.rules
dracut: *** Including module: mdraid ***
dracut: Skipping udev rule: 64-md-raid.rules
dracut: *** Including module: nvdimm ***
dracut: *** Including module: qemu ***
dracut: *** Including module: lunmask ***
dracut: *** Including module: resume ***
dracut: *** Including module: rootfs-block ***
dracut: *** Including module: terminfo ***
dracut: *** Including module: udev-rules ***
dracut: Skipping udev rule: 40-redhat.rules
dracut: Skipping udev rule: 50-firmware.rules
dracut: Skipping udev rule: 50-udev.rules
dracut: Skipping udev rule: 91-permissions.rules
dracut: Skipping udev rule: 80-drivers-modprobe.rules
dracut: *** Including module: virtfs ***
dracut: *** Including module: dracut-systemd ***
dracut: *** Including module: ostree ***
dracut: *** Including module: usrmount ***
dracut: *** Including module: base ***
dracut: *** Including module: fs-lib ***
dracut: *** Including module: memstrack ***
dracut: *** Including module: shutdown ***
dracut: *** Including modules done ***
dracut: *** Installing kernel module dependencies ***
dracut: *** Installing kernel module dependencies done ***
dracut: *** Resolving executable dependencies ***
dracut: *** Resolving executable dependencies done ***
dracut: *** Hardlinking files ***
dracut: Mode:           real
dracut: Files:          2896
dracut: Linked:         201 files
dracut: Compared:       0 xattrs
dracut: Compared:       935 files
dracut: Saved:          6.37 MiB
dracut: Duration:       0.086681 seconds
dracut: *** Hardlinking files done ***
dracut: *** Generating early-microcode cpio image ***
dracut: *** Constructing AuthenticAMD.bin ***
dracut: *** Constructing GenuineIntel.bin ***
dracut: *** Store current command line parameters ***
dracut: *** Stripping files ***
[...]
```

The logs continue for a few hundred more lines after this point.

**Comment by electricduck** [comment]
Did some research and some testing, and it turns out your mention of **Fedora 35** was actually quite important. Seems as if this would not build on my old 34 install (I know, I know, time for an upgrade!). Interestingly it also does work in SELinux's `enforcing` mode for me too :thinking:. As an added bonus it also built on Silverblue (35) itself.

However, not sure if you've observed this, but `remove-from-packages` and `remove-files` in the treefile fails to work. The way I'm proposing on fixing this until coreos/rpm-ostree#3270 is fixed is just to overwrite this files with empty files, like this:

```
add-files: [
    ["../include/sysroot/usr/share/wayland-sessions/gnome.desktop", "/usr/share/wayland-sessions/gnome.desktop"],
    # this file just contains the contents "# Removed"
...
```

Its hacky but it does seem to work, unless there is another way this can be accomplished?

Also in the process of creating a `Containerfile` for the build so there's less of this it-works-on-my-machine :+1:.

**Comment by ACertainTopfi** [comment]
Yeah, rpm-ostree has some issues running on older or newer versions of Fedora. I remember having issues building Rawhide trees on F35 in the past. Personally, I believe that overwriting the files is the better course of action in this case.

**Comment by electricduck** [comment]
Right, I have proposed these changes in feature/workaround-unified-core-bug.

**Comment by electricduck** [comment]
Closed with 86dfbf3ff1245882aae3bd2ff2dc4d96a91ad194.

**Comment by electricduck** [comment]
> Sodalite goes at such a project from a different direction, with each approach potentially complementing each other, so perhaps we can collaborate on that.

Forgot to ask, how would you like to go about that? Sounds fantastic :smile:

**Comment by ACertainTopfi** [comment]
Honestly, was impressed by the way you have gotten Sodalite beyond the pre-existing silverblue-pantheon.yaml. Everything feels a bit more cohesive in Sodalite compared to what I was working on up to this point. I was at this point mainly looking into how to best repackage and modify Anaconda for a more EOS style of installation.
